name: Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ secrets.SSH_KEY }}
        
        
    
    - uses: actions/setup-node@v3
      name: Setup Node ${{ matrix.node-version }}
      with:
        node-version: 16
        
    - uses: appleboy/ssh-action@master
      name: Checkout repo
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        username: ${{ secrets.SSH_USERNAME }}
        run: git clone git@github.com:ilyaem/cryptogrowth.git cryptogrowth
      
      
      
    - run: npm ci
    
    
    - runs: 
          echo 'Deployment completed'
          npm run build
          pm2 restart server
